CREATE SCHEMA IF NOT EXISTS aequitas;

CREATE OR REPLACE FUNCTION aequitas.strstr(left TEXT, right TEXT)
  RETURNS INTEGER
  AS 'MODULE_PATHNAME', 'pg_strstr'
  LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION aequitas.equals(left TEXT, right TEXT)
  RETURNS BOOLEAN
  AS 'MODULE_PATHNAME', 'pg_equals'
  LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;
